version: '3.1'
services: 
  odoo17:
    image: odoo:17
    container_name: odoo17_enterprise
    user: root
    ports:
      - "17000:8069"
      - "20019:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=icomm_crm
      - PASSWORD=icomm_2023
    networks:
          - odoo-16-docker-compose_default
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./addons_crm:/mnt/crm-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
networks:
  odoo-16-docker-compose_default:
    external: true