version: '3.1'
services:
  db:
    container_name: postgresql_odoo17
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=icomm_crm
      - POSTGRES_PASSWORD=icomm_2023      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - db-erp:/var/lib/postgresql/data

  odoo16:
    image: odoo:17
    container_name: odoo17_enterprise
    user: root
    depends_on:
      - db
    ports:
      - "17000:8069"
      - "20019:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=icomm_crm
      - PASSWORD=icomm_2023
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    restart: always             # run as a service
volumes:
  db-erp:
  odoo-web-data: