# -*- coding: utf-8 -*-  

{
    'name': 'History contact',
    'description': 'Customer journey',
    'summary': '',
    'category': '',
    "sequence": 3,
    'version': '1.0.0',
    'author': 'Duong Trung Hieu',
    'company': 'Company',
    'website': "",
    'depends': ['contacts', 'website_sale', 'crm', 'inherit_contact', 'mass_mailing', 'pontusinc_base_user'],
    'data': [
        'security/ir.model.access.csv',
        'data/data_tag_profiling.xml',
        'views/view_history_partner.xml',
        'views/view_partner_inherit.xml',
        'views/view_tag_profiling.xml',
        'views/update_product_view.xml',
        'views/shipping_view.xml',
        'views/menu_item.xml',
        'wizard/view_search_profiling.xml',
        'data/data_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'history_contact/static/scss/view.scss',
            'history_contact/static/src/phone_field.js',
            'history_contact/static/src/email_field.js',
            'history_contact/static/src/image_field.js',
            'history_contact/static/src/widget_phone/*',
            'history_contact/static/src/widget_email/*',
            'history_contact/static/src/views/*',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
