from . import loyalty_card
from . import loyalty_type
from . import loyalty_customer
from . import loyalty_rank
from . import loyalty_program
from . import loyalty_log
from . import res_company
from . import res_config_setting
from . import sale_order